### ISSUE TITLE
ImportError: No module named psycopg2.extensions

### ISSUE THREAD

**Issue by fkrebs** [philipsoutham/py-mysql2pgsql#75]
Hi
i am new in Python, so excuse my question

In windows 7,
I have been trying to install at first : <b>psycopg2-windows<b> :  https://github.com/nwcell/psycopg2-windows

<i>I run in DOS mode : </i>
setup.py install

<i>Result:</i>
    D:\soft\python\psycopg2-windows-0.1.0\psycopg2-windows-0.1.0>setup.py install
    C:\Python\Python27\lib\distutils\dist.py:267: UserWarning: Unknown distribution
    option: 'summary'
      warnings.warn(msg)
    running install
    running build
    running install_egg_info
    Writing C:\Python\Python27\Lib\site-packages\psycopg2-2.5.2-py2.7.egg-info

Then , i have been trying to install <b>py-mysql2pgsql</b> 
<i>I run in DOS:</i> 
D:\soft\python\py-mysql2pgsql-master>setup.py install

<i>Result : </i>
...
Finished processing dependencies for py-mysql2pgsql==0.1.6

When i <b>run the py-mysql2pgsql</b> script, i got a : <b>ImportError: No module named psycopg2.extensions</b>

<i>I run :</i> 
python py-mysql2pgsql -f 
D:\business_automation\processus_db\maintenance\export_mysql_import_postgresql\mysql_local_pg_local.yml    

<i>Result :</i>
C:\Python\Python27\Scripts>python py-mysql2pgsql -f D:\business_automation\processus_db\maintenance\export_mysql_import_postgresql\mysql_local_pg_local.yml
Traceback (most recent call last):
  File "py-mysql2pgsql", line 4, in <module>**import**('pkg_resources').run_script('py-mysql2pgsql==0.1.6', 'py-mysql2pgsql')
  File "C:\Python\Python27\lib\site-packages\pkg_resources.py", line 517, in run_script self.require(requires)[0].run_script(script_name, ns)
  File "C:\Python\Python27\lib\site-packages\pkg_resources.py", line 1436, in run_script exec(code, namespace, namespace)
  File "c:\python\python27\lib\site-packages\py_mysql2pgsql-0.1.6-py2.7.egg\EGG-INFO\scripts\py-mysql2pgsql", line 5, in <module> import mysql2pgsql
  File "C:\Python\Python27\lib\site-packages\py_mysql2pgsql-0.1.6-py2.7.egg\mysql2pgsql__init__.py", line 2, in <module>
    from .mysql2pgsql import Mysql2Pgsql
  File "C:\Python\Python27\lib\site-packages\py_mysql2pgsql-0.1.6-py2.7.egg\mysql2pgsql\mysql2pgsql.py", line 7, in <module>
    from .lib.postgres_file_writer import PostgresFileWriter
  File "C:\Python\Python27\lib\site-packages\py_mysql2pgsql-0.1.6-py2.7.egg\mysql2pgsql\lib\postgres_file_writer.py", line 6, in <module>
    from .postgres_writer import PostgresWriter
  File "C:\Python\Python27\lib\site-packages\py_mysql2pgsql-0.1.6-py2.7.egg\mysql2pgsql\lib\postgres_writer.py", line 7, in <module>
    from psycopg2.extensions import QuotedString, Binary, AsIs
ImportError: No module named psycopg2.extensions

What did i miss there ?
The setup.py install isn't sufficient to get all dependencies ?

Thanks

**Comment by kworr** [comment]
Probably this should be turned to https://github.com/nwcell/psycopg2-windows
